/**
 * AI Mock Interview — Grounded Question Bank
 *
 * Implements Section 7 (Question Framework) and Appendix A.
 * Each entry contains: prompt, reference answer, key points checklist,
 * common mistakes, follow-ups, hint ladder, and (for coding) test cases.
 *
 * Two tracks: Software Engineer (swe) and AI/ML Engineer (ai_ml)
 * Years: 2nd year (fundamentals-heavy) and 3rd year (deeper, project deep-dive)
 * Sections: warmup, fundamentals, problem_solving, project_or_design, behavioural, wrap_up
 *
 * v1: ~110 questions — covers all blueprint areas. Designed for variant generation
 * (Section 8.2 FR-18) and anti-repetition (no repeat within last 3 sessions).
 */

import type { InterviewQuestion, InterviewTrack, InterviewYear } from './types.ts'

export const QUESTION_BANK: InterviewQuestion[] = [
  // ───────────────────────────────────────────────────────────
  // WARMUP (both tracks)
  // ───────────────────────────────────────────────────────────
  {
    id: 'warmup-intro-01',
    track: 'both',
    section: 'warmup',
    topic: ['introduction'],
    difficulty: 1,
    years: [2, 3],
    type: 'warmup',
    prompt: 'Tell me about yourself — your background, what you are studying, and what excites you about software engineering.',
    reference_answer: 'Brief intro: name, year, branch, 1-2 projects, tech interests, career goal. STAR-lite structure, 60-90s.',
    key_points: ['Mentions year/branch', 'Mentions 1-2 projects or interests', 'Clear career motivation', 'Concise 60-90s structure'],
    common_mistakes: ['Too long life story', 'No technical content', 'Rambling without structure'],
    follow_ups: ['What got you interested in programming?', 'What are you currently learning outside coursework?'],
    hint_ladder: ['Start with your current year and branch', 'Mention one project you enjoyed', 'Connect your interest to this track'],
    time_limit_min: 3,
  },
  {
    id: 'warmup-intro-02',
    track: 'both',
    section: 'warmup',
    topic: ['introduction', 'motivation'],
    difficulty: 1,
    years: [2, 3],
    type: 'warmup',
    prompt: 'Why did you choose the {track} track for this mock interview?',
    reference_answer: 'Links personal interest and career goal to track. Shows awareness of track scope.',
    key_points: ['States reason for track choice', 'Shows awareness of track scope', 'Links to past experience or goal'],
    common_mistakes: ['Generic answer', 'No connection to experience'],
    follow_ups: ['How does this align with your placement goals?'],
    hint_ladder: ['Think about what you enjoy building', 'What kind of role are you aiming for?', 'Connect past project to track'],
    time_limit_min: 2,
  },

  // ───────────────────────────────────────────────────────────
  // FUNDAMENTALS — SWE Y2
  // ───────────────────────────────────────────────────────────
  {
    id: 'swe-oop-01',
    track: 'swe',
    section: 'fundamentals',
    topic: ['oop', 'java', 'abstraction'],
    difficulty: 1,
    years: [2, 3],
    type: 'conceptual',
    prompt: 'Explain abstract class vs interface. When would you use each? Give an example.',
    reference_answer: 'Abstract class: partial implementation, single inheritance, state. Interface: contract, multiple inheritance, default methods since Java 8. Use abstract when sharing code, interface when defining capability.',
    key_points: ['Contract vs partial implementation', 'Single vs multiple inheritance', 'State in abstract class', 'Example like Payment hierarchy'],
    common_mistakes: ['Says they are same', 'Forgets multiple inheritance', 'No example'],
    follow_ups: ['Design a Payment class hierarchy using both.', 'What changed with default methods in interfaces?'],
    hint_ladder: ['Think about what each can contain — methods vs implementation', 'Can a class implement multiple interfaces?', 'When would sharing code matter?'],
    time_limit_min: 4,
  },
  {
    id: 'swe-oop-02',
    track: 'swe',
    section: 'fundamentals',
    topic: ['oop', 'polymorphism'],
    difficulty: 1,
    years: [2],
    type: 'conceptual',
    prompt: 'What is polymorphism? Explain compile-time vs runtime polymorphism with examples.',
    reference_answer: 'Compile-time: overloading same name different params resolved at compile. Runtime: overriding via inheritance, resolved via vtable at runtime. Example Animal speak().',
    key_points: ['Overloading vs overriding', 'Compile vs runtime resolution', 'Example with inheritance'],
    common_mistakes: ['Mixes overloading and overriding', 'No example'],
    follow_ups: ['How does the JVM resolve overridden methods?', 'Can you overload by return type alone?'],
    hint_ladder: ['Think about same method name, different parameters', 'What about child class changing parent behavior?', 'When is decision made?'],
    time_limit_min: 3,
  },
  {
    id: 'swe-dsa-array-01',
    track: 'swe',
    section: 'fundamentals',
    topic: ['arrays', 'hashing'],
    difficulty: 1,
    years: [2, 3],
    type: 'conceptual',
    prompt: 'How does a hash map work internally? What happens on collision and how do you handle resizing?',
    reference_answer: 'Hash function -> bucket index, array of buckets with chaining or open addressing. Load factor triggers resize rehashing. Average O(1), worst O(n) or O(log n) with tree bins.',
    key_points: ['Hashing into buckets', 'Chaining or open addressing', 'Load factor and resizing', 'Average O(1) vs worst case'],
    common_mistakes: ['Says hash map is always O(1)', 'No collision handling', 'Ignores resizing'],
    follow_ups: ['How would you design a hash function for strings?', 'Why does Java 8 use trees in HashMap bins?'],
    hint_ladder: ['What converts key to array index?', 'What if two keys map to same index?', 'What happens when map gets too full?'],
    time_limit_min: 4,
  },
  {
    id: 'swe-dbms-01',
    track: 'swe',
    section: 'fundamentals',
    topic: ['dbms', 'normalization'],
    difficulty: 1,
    years: [2, 3],
    type: 'conceptual',
    prompt: 'What is normalization? Explain 1NF, 2NF, 3NF and why we need them.',
    reference_answer: 'Remove redundancy/anomalies. 1NF atomic values, 2NF no partial dependency on composite key, 3NF no transitive dependency. Tradeoff with query performance.',
    key_points: ['Purpose: reduce redundancy/anomalies', '1NF atomic values', '2NF no partial dependency', '3NF no transitive dependency'],
    common_mistakes: ['Cannot explain anomalies', 'Mixes 2NF and 3NF', 'No tradeoff mention'],
    follow_ups: ['When would you denormalize?', 'Give example of update anomaly.'],
    hint_ladder: ['Why is storing same data twice bad?', 'What if table has composite key and column depends only on part?', 'What about column depending on non-key column?'],
    time_limit_min: 4,
  },
  {
    id: 'swe-dbms-02',
    track: 'swe',
    section: 'fundamentals',
    topic: ['sql', 'indexes'],
    difficulty: 2,
    years: [2, 3],
    type: 'conceptual',
    prompt: 'What is a database index? How does a B-Tree index work and what are its tradeoffs? Also write a query to find second highest salary.',
    reference_answer: 'Index speeds reads via B-Tree structure O(log n) lookup, costs writes and storage. Query: SELECT MAX(salary) WHERE salary < (SELECT MAX...), or DENSE_RANK window.',
    key_points: ['B-Tree structure for range queries', 'Speeds reads, slows writes', 'Storage overhead', 'Second-highest query with subquery or window function'],
    common_mistakes: ['Says index always good', 'Forgets write cost', 'Wrong second-highest query'],
    follow_ups: ['When would an index hurt performance?', 'Clustered vs non-clustered index?'],
    hint_ladder: ['How do you find a word in a dictionary quickly?', 'What happens on INSERT with many indexes?', 'How to get second highest without sorting whole table?'],
    time_limit_min: 5,
  },
  {
    id: 'swe-os-01',
    track: 'swe',
    section: 'fundamentals',
    topic: ['os', 'process', 'thread'],
    difficulty: 2,
    years: [3],
    type: 'conceptual',
    prompt: 'Explain process vs thread. What is a deadlock and what are the four Coffman conditions? How can it be prevented?',
    reference_answer: 'Process isolated address space, thread shares memory within process, lighter context switch. Deadlock: mutual exclusion, hold and wait, no preemption, circular wait. Prevention breaks one condition, avoidance via Banker algorithm.',
    key_points: ['Process vs thread memory/context switch', 'Four Coffman conditions listed', 'Prevention vs avoidance', 'Example of deadlock'],
    common_mistakes: ['Says threads have separate memory', 'Forgets Coffman conditions', 'No prevention'],
    follow_ups: ['What is a race condition and how to prevent?', 'Explain virtual memory briefly.'],
    hint_ladder: ['Who owns memory — process or thread?', 'What must hold for deadlock to happen?', 'How to break circular wait?'],
    time_limit_min: 5,
  },
  {
    id: 'swe-cn-01',
    track: 'swe',
    section: 'fundamentals',
    topic: ['cn', 'http', 'dns'],
    difficulty: 2,
    years: [3],
    type: 'conceptual',
    prompt: 'What happens when you type a URL into a browser and press Enter? Walk through DNS, TCP, TLS, HTTP and rendering.',
    reference_answer: 'DNS lookup -> TCP 3-way handshake -> TLS handshake -> HTTP request/response -> HTML parse, CSSOM, JS, render tree, paint. Caching at each layer.',
    key_points: ['DNS resolution', 'TCP 3-way handshake', 'TLS handshake', 'HTTP request/response and rendering steps'],
    common_mistakes: ['Skips DNS or TLS', 'No TCP handshake', 'No rendering'],
    follow_ups: ['What is the difference between HTTP 1.1, 2 and 3?', 'How does CDN help?'],
    hint_ladder: ['How does browser know IP from domain?', 'How is reliable connection established?', 'What happens after browser gets HTML?'],
    time_limit_min: 5,
  },

  // ───────────────────────────────────────────────────────────
  // PROBLEM SOLVING — SWE
  // ───────────────────────────────────────────────────────────
  {
    id: 'swe-coding-twosum-01',
    track: 'swe',
    section: 'problem_solving',
    topic: ['arrays', 'hashing'],
    difficulty: 1,
    years: [2, 3],
    type: 'coding',
    prompt: 'Given an array of integers nums and an integer target, return indices of two numbers that add up to target. You may not use the same element twice. Example: nums=[2,7,11,15], target=9 => [0,1]. Explain your approach and complexity.',
    reference_answer: 'Brute force O(n^2) checks all pairs. Optimized: hash map value->index, single pass O(n) time O(n) space. Handle duplicates and no-solution.',
    key_points: ['States brute force O(n^2) first', 'Uses hash map for O(n)', 'Handles duplicates and no-solution', 'States time and space complexity'],
    common_mistakes: ['Uses same element twice', 'Sorts and loses indices', 'No complexity analysis'],
    follow_ups: ['What if array is sorted? Two pointers O(n) O(1) space.', 'What if memory is limited?'],
    hint_ladder: ['What repeated work does brute force do?', 'Which data structure gives fast lookups?', 'For each x, look up target-x in a map.'],
    time_limit_min: 10,
    coding_spec: {
      fn_name: { python: 'twoSum', javascript: 'twoSum', java: 'twoSum', cpp: 'twoSum', c: 'twoSum', rust: 'two_sum', go: 'twoSum' } as any,
      starter_code: {
        python: 'def twoSum(nums, target):\n    # return list of two indices\n    pass',
        javascript: 'function twoSum(nums, target) {\n  // return [i,j]\n}',
        java: 'class Solution { public int[] twoSum(int[] nums, int target) { return new int[0]; } }',
        cpp: '#include <bits/stdc++.h>\nusing namespace std;\nvector<int> twoSum(vector<int>& nums, int target) { return {}; }',
        c: '#include <stdio.h>\nint* twoSum(int* nums, int numsSize, int target, int* returnSize) { return NULL; }',
        rust: 'fn two_sum(nums: Vec<i32>, target: i32) -> Vec<i32> { vec![] }',
        go: 'func twoSum(nums []int, target int) []int { return []int{} }',
      } as any,
      compare: 'unordered',
      tests: [
        { name: 'example [2,7,11,15] target 9', args: [[2, 7, 11, 15], 9], expected: [0, 1], sample: true },
        { name: 'duplicate values [3,3] target 6', args: [[3, 3], 6], expected: [0, 1] },
        { name: 'negative numbers', args: [[-1, -2, -3, -4, -5], -8], expected: [2, 4] },
        { name: 'large array 1000 elements', args: [{ $gen: 'distinct', n: 1000, lo: -10000, hi: 10000, seed: 42 }, 99999], expected: { $digest: 'placeholder' } },
      ] as any,
      sample_input_output: [{ input: 'nums=[2,7,11,15], target=9', output: '[0,1]', explanation: 'nums[0]+nums[1]=9' }],
      target_complexity: 'O(n) time, O(n) space',
    },
  },
  {
    id: 'swe-coding-cycle-01',
    track: 'swe',
    section: 'problem_solving',
    topic: ['linked-list', 'two-pointers'],
    difficulty: 2,
    years: [2, 3],
    type: 'coding',
    prompt: 'How would you detect a cycle in a linked list? Explain Floyd’s Tortoise and Hare algorithm, its complexity, and how to find the start of the cycle.',
    reference_answer: 'Slow moves 1 step, fast 2 steps. If they meet, cycle exists. To find start: reset one to head, move both 1 step until meet. O(n) time O(1) space.',
    key_points: ['Two pointers slow/fast', 'Meeting means cycle', 'O(1) space', 'Finds cycle start by resetting one pointer'],
    common_mistakes: ['Uses hash set and claims O(1) space', 'Cannot find start', 'No complexity'],
    follow_ups: ['What is the math behind why it works?', 'How to find length of cycle?'],
    hint_ladder: ['What if one pointer moves faster than other?', 'If there is cycle, will fast ever catch slow?', 'How to find entry point after detection?'],
    time_limit_min: 8,
  },
  {
    id: 'swe-coding-bfs-01',
    track: 'swe',
    section: 'problem_solving',
    topic: ['graphs', 'bfs'],
    difficulty: 2,
    years: [3],
    type: 'coding',
    prompt: 'Find shortest path in an unweighted graph from source to all nodes. Which algorithm and why? What about weighted graph?',
    reference_answer: 'BFS with queue and visited set gives shortest path in unweighted O(V+E). For weighted, Dijkstra with min-heap O((V+E) log V).',
    key_points: ['BFS for unweighted shortest path', 'Queue and visited set', 'O(V+E) complexity', 'Dijkstra for weighted'],
    common_mistakes: ['Uses DFS for shortest path', 'Forgets visited set', 'Wrong complexity'],
    follow_ups: ['BFS vs DFS memory usage?', 'What if graph has negative weights?'],
    hint_ladder: ['Which traversal explores level by level?', 'How to avoid revisiting nodes?', 'What changes when edges have weights?'],
    time_limit_min: 7,
  },
  {
    id: 'swe-coding-dp-01',
    track: 'swe',
    section: 'problem_solving',
    topic: ['dp', 'recursion'],
    difficulty: 3,
    years: [3],
    type: 'coding',
    prompt: 'Solve coin change: given coins and amount, find minimum number of coins to make amount, or -1 if impossible. Explain recurrence and DP table.',
    reference_answer: 'Recurrence dp[0]=0, dp[i]=min(dp[i-coin]+1). Bottom-up O(amount * coins) time O(amount) space. BFS also works.',
    key_points: ['Recurrence dp[i]=min(dp[i-coin]+1)', 'Base case dp[0]=0', 'Bottom-up tabulation', 'Handles impossible case'],
    common_mistakes: ['Greedy fails for arbitrary coins', 'No handling of impossible', 'Wrong complexity'],
    follow_ups: ['How to reconstruct coins used?', 'What if you need number of ways?'],
    hint_ladder: ['Think recursively: to make amount, try each coin last', 'What subproblem do you need?', 'Can you build answer from smaller amounts?'],
    time_limit_min: 12,
  },

  // ───────────────────────────────────────────────────────────
  // PROJECT / DESIGN — SWE
  // ───────────────────────────────────────────────────────────
  {
    id: 'swe-project-01',
    track: 'swe',
    section: 'project_or_design',
    topic: ['project', 'ownership'],
    difficulty: 1,
    years: [2, 3],
    type: 'project',
    prompt: 'Walk me through your best project. What was hardest, what trade-offs did you make, and what would you change if you rebuilt it?',
    reference_answer: 'Structured: context, tech stack, ownership, hardest challenge, trade-offs, failure, learning, what would change. Shows honesty and depth.',
    key_points: ['Clear context and tech stack', 'Personal ownership explained', 'Trade-offs discussed', 'Honesty about limits and improvements'],
    common_mistakes: ['Vague project description', 'No personal contribution', 'No trade-offs'],
    follow_ups: ['Why did you choose that database?', 'How would you scale it to 1M users?', 'What was a bug you missed?'],
    hint_ladder: ['Start with what problem project solves', 'What part did you personally build?', 'If you had 2 more weeks, what would you improve?'],
    time_limit_min: 6,
  },
  {
    id: 'swe-design-01',
    track: 'swe',
    section: 'project_or_design',
    topic: ['system-design', 'scalability'],
    difficulty: 3,
    years: [3],
    type: 'design',
    prompt: 'Design a URL shortener like bit.ly at a high level. Cover requirements, API, data model, scaling and caching.',
    reference_answer: 'Req: short URL, redirect, expiry, analytics. API POST /shorten, GET /{code}. DB: mapping table. Base62 encoding or hash. Cache hot URLs in Redis. Scale: sharding, CDN, rate limiting.',
    key_points: ['Requirements and API design', 'Base62 or hash for code generation', 'Database choice and schema', 'Caching and scale considerations'],
    common_mistakes: ['No API design', 'No collision handling', 'Ignores scaling'],
    follow_ups: ['How to handle custom aliases?', 'How to prevent abuse?', 'How to handle 1B URLs?'],
    hint_ladder: ['What does user send and receive?', 'How to convert long URL to short code?', 'Where would caching help?'],
    time_limit_min: 8,
  },

  // ───────────────────────────────────────────────────────────
  // BEHAVIOURAL — SWE
  // ───────────────────────────────────────────────────────────
  {
    id: 'swe-behavioural-01',
    track: 'swe',
    section: 'behavioural',
    topic: ['behavioural', 'teamwork'],
    difficulty: 1,
    years: [2, 3],
    type: 'behavioural',
    prompt: 'Tell me about a time a team project went wrong. How did you handle it and what did you learn? Use STAR structure.',
    reference_answer: 'STAR: Situation team missed deadline, Task my role, Action communication, prioritization, help, Result delivered with learning about early escalation.',
    key_points: ['Uses STAR structure', 'Personal accountability', 'Concrete actions taken', 'Learning reflected'],
    common_mistakes: ['Blames others', 'No structure', 'No learning'],
    follow_ups: ['How do you handle disagreements now?', 'What would you do differently?'],
    hint_ladder: ['Describe situation and your role', 'What specific action did you take?', 'What did you learn from it?'],
    time_limit_min: 4,
  },
  {
    id: 'swe-behavioural-02',
    track: 'swe',
    section: 'behavioural',
    topic: ['behavioural', 'conflict'],
    difficulty: 2,
    years: [3],
    type: 'behavioural',
    prompt: 'Describe a situation where you disagreed with a teammate on a technical decision. How did you resolve it?',
    reference_answer: 'Shows listening, data-driven decision, compromise, team first. Not ego-driven.',
    key_points: ['Shows listening and empathy', 'Data or prototype to decide', 'Resolution and outcome', 'Maintains relationship'],
    common_mistakes: ['Says they were always right', 'No resolution', 'Personal attack'],
    follow_ups: ['How do you give feedback to a senior?', 'When do you escalate?'],
    hint_ladder: ['What was disagreement about?', 'How did you understand other perspective?', 'How did you decide?'],
    time_limit_min: 4,
  },

  // ───────────────────────────────────────────────────────────
  // FUNDAMENTALS — AI/ML Y2 & Y3
  // ───────────────────────────────────────────────────────────
  {
    id: 'aiml-python-01',
    track: 'ai_ml',
    section: 'fundamentals',
    topic: ['python', 'numpy'],
    difficulty: 1,
    years: [2, 3],
    type: 'conceptual',
    prompt: 'What is the difference between a Python list and a NumPy array? What is vectorization and why is it faster?',
    reference_answer: 'List: heterogeneous, pointer array, Python loops. NumPy: homogeneous, contiguous C array, vectorized ops in C, broadcasting, memory efficient.',
    key_points: ['Homogeneous vs heterogeneous', 'Contiguous memory vs pointers', 'Vectorization in C', 'Broadcasting'],
    common_mistakes: ['Says they are same', 'No memory layout', 'No speed reason'],
    follow_ups: ['How to avoid Python loop for dot product?', 'What is broadcasting example?'],
    hint_ladder: ['How is data stored in memory for each?', 'Why would C loop be faster than Python loop?', 'Can you add arrays of different shapes?'],
    time_limit_min: 4,
  },
  {
    id: 'aiml-math-01',
    track: 'ai_ml',
    section: 'fundamentals',
    topic: ['math', 'gradient-descent'],
    difficulty: 2,
    years: [2, 3],
    type: 'conceptual',
    prompt: 'Explain gradient descent. What happens if learning rate is too high or too low? Mention variants like SGD and Adam.',
    reference_answer: 'Iterative optimization following negative gradient to minimize loss. Too high diverges, too low slow or stuck. SGD noisy, Adam adaptive moments.',
    key_points: ['Loss surface and negative gradient', 'Too high diverges, too low slow', 'SGD vs Adam difference', 'Learning rate scheduling'],
    common_mistakes: ['No intuition', 'Confuses learning rate with loss', 'No variants'],
    follow_ups: ['What is vanishing gradient?', 'How to choose learning rate?'],
    hint_ladder: ['What direction reduces loss?', 'What if you take huge steps?', 'What if steps are tiny?'],
    time_limit_min: 5,
  },
  {
    id: 'aiml-ml-01',
    track: 'ai_ml',
    section: 'fundamentals',
    topic: ['ml', 'overfitting'],
    difficulty: 1,
    years: [2, 3],
    type: 'conceptual',
    prompt: 'Explain overfitting vs underfitting. How do you detect and fix each?',
    reference_answer: 'Overfitting: train low, val high gap, memorizes noise. Fix regularization, more data, simpler model, early stopping. Underfitting: both high, model too simple.',
    key_points: ['Train vs validation gap definition', 'Overfitting fixes: regularization, more data', 'Underfitting: model too simple', 'Early stopping and cross-validation'],
    common_mistakes: ['Reverses over and under', 'No detection method', 'No fixes'],
    follow_ups: ['What is bias-variance tradeoff?', 'How does dropout help?'],
    hint_ladder: ['What if model memorizes training data?', 'How to tell from train vs validation curves?', 'What makes model simpler?'],
    time_limit_min: 4,
  },
  {
    id: 'aiml-ml-02',
    track: 'ai_ml',
    section: 'fundamentals',
    topic: ['ml', 'metrics', 'classification'],
    difficulty: 1,
    years: [2, 3],
    type: 'conceptual',
    prompt: 'When does accuracy mislead? Explain precision, recall, F1 and when you would prioritize each.',
    reference_answer: 'Imbalanced classes: 95% accuracy with 5% positives is useless. Precision TP/(TP+FP) for costly false positives, Recall TP/(TP+FN) for costly false negatives, F1 harmonic mean.',
    key_points: ['Class imbalance example', 'Precision vs recall formulas', 'Tradeoff and use cases', 'F1 as harmonic mean'],
    common_mistakes: ['Says accuracy always good', 'Mixes precision/recall', 'No example'],
    follow_ups: ['What is ROC-AUC?', 'When would you use PR-AUC over ROC?'],
    hint_ladder: ['What if 99% data is one class?', 'If false alarm is expensive, which metric matters?', 'If missing a case is dangerous?'],
    time_limit_min: 4,
  },
  {
    id: 'aiml-data-01',
    track: 'ai_ml',
    section: 'fundamentals',
    topic: ['data', 'preprocessing'],
    difficulty: 2,
    years: [2, 3],
    type: 'conceptual',
    prompt: 'Your dataset has missing values and outliers. Walk me through how you would handle them and avoid data leakage.',
    reference_answer: 'Diagnose why missing (MCAR etc), imputation mean/median/mode or model, flag missing. Outliers: robust scaling, clipping, isolation forest. Avoid leakage by fit on train only, pipeline.',
    key_points: ['Diagnose reason for missing', 'Imputation options', 'Outlier handling', 'Avoid leakage by fitting on train only'],
    common_mistakes: ['Always drops rows', 'Imputes before split causing leakage', 'Ignores why missing'],
    follow_ups: ['What is data leakage example?', 'How to handle categorical missing?'],
    hint_ladder: ['Why might data be missing?', 'If you fill missing before split, what leaks?', 'How to detect outliers?'],
    time_limit_min: 5,
  },
  {
    id: 'aiml-ml-03',
    track: 'ai_ml',
    section: 'fundamentals',
    topic: ['ml', 'ensemble', 'random-forest'],
    difficulty: 2,
    years: [3],
    type: 'conceptual',
    prompt: 'How does a random forest work? Why do ensembles help? What are its limitations?',
    reference_answer: 'Bagging: bootstrap samples, random feature subsets per split, vote/average. Reduces variance, handles overfitting vs single tree. Limitations: less interpretable, slower, not good for extrapolation.',
    key_points: ['Bagging and bootstrap', 'Feature randomness', 'Variance reduction', 'Limitations: interpretability, speed'],
    common_mistakes: ['Says boosting not bagging', 'No variance reduction', 'No limitations'],
    follow_ups: ['Random forest vs gradient boosting?', 'How to tune number of trees?'],
    hint_ladder: ['What if you train many trees on different subsets?', 'Why would averaging help?', 'What does random forest lose vs single tree?'],
    time_limit_min: 5,
  },
  {
    id: 'aiml-dl-01',
    track: 'ai_ml',
    section: 'fundamentals',
    topic: ['deep-learning', 'backpropagation'],
    difficulty: 2,
    years: [3],
    type: 'conceptual',
    prompt: 'What is backpropagation? Why do we need activation functions? What is vanishing gradient?',
    reference_answer: 'Chain rule to compute gradients backwards, update weights via GD. Activation adds non-linearity, otherwise deep net is linear. Vanishing: gradients shrink in deep nets with sigmoid, mitigated by ReLU, residual connections.',
    key_points: ['Chain rule for gradients', 'Non-linearity from activation', 'Vanishing gradient explanation', 'ReLU/residual as fix'],
    common_mistakes: ['No chain rule', 'Says activation optional', 'No vanishing explanation'],
    follow_ups: ['Why ReLU and not sigmoid in hidden layers?', 'What is exploding gradient?'],
    hint_ladder: ['How to compute derivative of composed functions?', 'What if all layers are linear?', 'What happens to gradient through many sigmoids?'],
    time_limit_min: 5,
  },
  {
    id: 'aiml-dl-02',
    track: 'ai_ml',
    section: 'fundamentals',
    topic: ['transformers', 'attention'],
    difficulty: 3,
    years: [3],
    type: 'conceptual',
    prompt: 'Why did transformers largely replace RNNs? Explain attention at a high level.',
    reference_answer: 'Attention allows parallel processing, captures long-range dependencies without sequential bottleneck, better scaling. Self-attention: QK dot product, softmax, weighted sum of V. Positional encoding for order.',
    key_points: ['Parallelism vs sequential RNN', 'Long-range dependencies', 'Self-attention QKV intuition', 'Positional encoding'],
    common_mistakes: ['Says RNN faster', 'No attention explanation', 'No parallelism point'],
    follow_ups: ['What is the cost of attention at long context?', 'What is causal masking?'],
    hint_ladder: ['What is bottleneck of processing word by word?', 'How can every word look at every other word?', 'Why still need position info?'],
    time_limit_min: 5,
  },
  {
    id: 'aiml-genai-01',
    track: 'ai_ml',
    section: 'fundamentals',
    topic: ['genai', 'rag', 'hallucination'],
    difficulty: 3,
    years: [3],
    type: 'conceptual',
    prompt: 'What is RAG? When would you use it instead of fine-tuning? How do you reduce hallucinations?',
    reference_answer: 'Retrieval Augmented Generation: retrieve relevant docs via embeddings, feed to LLM to generate grounded answer. Use RAG for fresh knowledge, fine-tune for behavior/style. Reduce hallucinations via grounding, citation, evaluation, chunking, reranking.',
    key_points: ['Retrieval + generation definition', 'RAG vs fine-tuning tradeoffs', 'Hallucination reduction techniques', 'Chunking and embeddings'],
    common_mistakes: ['Says RAG is fine-tuning', 'No hallucination mitigation', 'No embeddings mention'],
    follow_ups: ['How to evaluate RAG?', 'What is vector database?', 'When would you still fine-tune?'],
    hint_ladder: ['What if LLM knowledge is outdated?', 'How to give LLM fresh documents?', 'How to make LLM cite sources?'],
    time_limit_min: 6,
  },
  {
    id: 'aiml-genai-02',
    track: 'ai_ml',
    section: 'fundamentals',
    topic: ['embeddings', 'vector-search'],
    difficulty: 2,
    years: [3],
    type: 'conceptual',
    prompt: 'What are embeddings and how does vector similarity search work? What is ANN and why needed?',
    reference_answer: 'Dense vectors capturing semantic meaning. Similarity via cosine or dot product. ANN (HNSW, IVF) approximates nearest neighbors fast for large scale, tradeoff recall vs latency.',
    key_points: ['Dense semantic vectors', 'Cosine similarity', 'ANN for scale', 'Use cases like search, RAG, clustering'],
    common_mistakes: ['Confuses with one-hot', 'No similarity metric', 'No ANN reason'],
    follow_ups: ['How to evaluate embedding quality?', 'What is the difference between dense and sparse retrieval?'],
    hint_ladder: ['How to represent meaning as numbers?', 'How to find similar meaning?', 'What if you have 10M vectors?'],
    time_limit_min: 4,
  },

  // ───────────────────────────────────────────────────────────
  // PROBLEM SOLVING — AI/ML
  // ───────────────────────────────────────────────────────────
  {
    id: 'aiml-coding-pandas-01',
    track: 'ai_ml',
    section: 'problem_solving',
    topic: ['python', 'pandas', 'data-wrangling'],
    difficulty: 2,
    years: [2, 3],
    type: 'coding',
    prompt: 'Given a pandas DataFrame with columns user_id, event, timestamp, write code to find daily active users (DAU) and 7-day retention. Explain approach.',
    reference_answer: 'Group by date, count distinct users for DAU. Retention: cohort by first seen date, check if user active 7 days later. Use pd.to_datetime, groupby, nunique.',
    key_points: ['DAU via groupby date nunique', 'Cohort retention logic', 'Handles timestamp parsing', 'Complexity discussion'],
    common_mistakes: ['Counts events not users', 'No cohort logic', 'No handling of timezones'],
    follow_ups: ['How to handle large data that does not fit in memory?', 'What if you need hourly DAU?'],
    hint_ladder: ['How to get date from timestamp?', 'How to count unique users per day?', 'How to track if user returns after 7 days?'],
    time_limit_min: 10,
  },
  {
    id: 'aiml-coding-knn-01',
    track: 'ai_ml',
    section: 'problem_solving',
    topic: ['ml', 'knn', 'implementation'],
    difficulty: 2,
    years: [3],
    type: 'coding',
    prompt: 'Implement k-NN from scratch (no sklearn). Include Euclidean distance, majority vote, and discuss choosing k.',
    reference_answer: 'Compute distances, sort, take k nearest, majority vote. Choose k via cross-validation, odd k to avoid ties, small k overfits, large k underfits.',
    key_points: ['Euclidean distance implementation', 'Majority vote', 'Choosing k via cross-validation', 'Complexity O(n*d) per query'],
    common_mistakes: ['Uses library', 'No tie handling', 'No complexity'],
    follow_ups: ['How to speed up k-NN for large data?', 'What about weighted k-NN?'],
    hint_ladder: ['How to measure distance between points?', 'How to decide label from neighbors?', 'What happens if k is too small or too large?'],
    time_limit_min: 12,
  },
  {
    id: 'aiml-coding-metric-01',
    track: 'ai_ml',
    section: 'problem_solving',
    topic: ['ml', 'metrics', 'implementation'],
    difficulty: 1,
    years: [2, 3],
    type: 'coding',
    prompt: 'Implement precision, recall, F1 from scratch given y_true and y_pred lists. Handle edge cases like zero division.',
    reference_answer: 'Count TP, FP, FN, TN. Precision TP/(TP+FP), Recall TP/(TP+FN), F1 2PR/(P+R). Handle zero division return 0.',
    key_points: ['TP FP FN counting', 'Formulas correct', 'Handles zero division', 'Explains tradeoff'],
    common_mistakes: ['Mixes precision/recall', 'No zero division handling', 'Wrong counting'],
    follow_ups: ['How to extend to multiclass?', 'What about macro vs micro average?'],
    hint_ladder: ['What is true positive?', 'How to compute precision from counts?', 'What if denominator is zero?'],
    time_limit_min: 8,
  },

  // ───────────────────────────────────────────────────────────
  // PROJECT / DESIGN — AI/ML
  // ───────────────────────────────────────────────────────────
  {
    id: 'aiml-project-01',
    track: 'ai_ml',
    section: 'project_or_design',
    topic: ['project', 'ml', 'evaluation'],
    difficulty: 2,
    years: [2, 3],
    type: 'project',
    prompt: 'Walk me through an ML project you built. Cover data, model choice, evaluation, and what you would improve.',
    reference_answer: 'Structured: problem framing, data source and cleaning, features, model selection, metrics, evaluation, deployment if any, failures and improvements.',
    key_points: ['Problem framing', 'Data and features', 'Model choice justification', 'Evaluation and improvements'],
    common_mistakes: ['Only says used model', 'No evaluation', 'No data discussion'],
    follow_ups: ['How did you avoid leakage?', 'What was hardest part?', 'How would you deploy?'],
    hint_ladder: ['What problem were you solving?', 'What data did you use?', 'How did you know model was good?'],
    time_limit_min: 7,
  },
  {
    id: 'aiml-case-01',
    track: 'ai_ml',
    section: 'project_or_design',
    topic: ['case-study', 'dropout', 'mlops'],
    difficulty: 3,
    years: [3],
    type: 'design',
    prompt: 'Build a model to predict student dropout: data, features, metric, pitfalls, fairness and monitoring.',
    reference_answer: 'Frame as classification, features academic, engagement, demographic (careful), metric recall for at-risk, pitfalls leakage (future data), fairness across groups, monitoring drift.',
    key_points: ['Problem framing as classification', 'Features and leakage risks', 'Metric choice justification', 'Fairness and monitoring'],
    common_mistakes: ['Uses accuracy only', 'No leakage discussion', 'No fairness'],
    follow_ups: ['How to handle class imbalance?', 'How to explain predictions to faculty?'],
    hint_ladder: ['What data would help predict dropout?', 'What could leak future info?', 'What if model is biased against a group?'],
    time_limit_min: 10,
  },
  {
    id: 'aiml-ethics-01',
    track: 'ai_ml',
    section: 'project_or_design',
    topic: ['ethics', 'bias', 'responsible-ai'],
    difficulty: 2,
    years: [3],
    type: 'conceptual',
    prompt: 'How can bias enter an ML system, and what can you do about it? Give concrete examples.',
    reference_answer: 'Bias via data collection, labeling, feature selection, feedback loops. Examples hiring, facial recognition. Mitigation audits, diverse data, fairness metrics, human review.',
    key_points: ['Sources: data, labels, features, feedback loops', 'Concrete example', 'Mitigation: audits, metrics', 'Human in loop'],
    common_mistakes: ['Says bias is only data', 'No example', 'No mitigation'],
    follow_ups: ['What is fairness vs accuracy tradeoff?', 'How to audit a model?'],
    hint_ladder: ['Where does training data come from?', 'What if labels reflect past discrimination?', 'How would you check for bias?'],
    time_limit_min: 5,
  },

  // ───────────────────────────────────────────────────────────
  // BEHAVIOURAL — AI/ML
  // ───────────────────────────────────────────────────────────
  {
    id: 'aiml-behavioural-01',
    track: 'ai_ml',
    section: 'behavioural',
    topic: ['behavioural', 'learning'],
    difficulty: 1,
    years: [2, 3],
    type: 'behavioural',
    prompt: 'Tell me about a time you learned a new ML concept or tool quickly to solve a problem.',
    reference_answer: 'STAR: needed transformers for project, learned via docs/course, built prototype, got feedback, improved.',
    key_points: ['STAR structure', 'Learning approach', 'Application to problem', 'Reflection'],
    common_mistakes: ['Vague', 'No concrete learning steps', 'No outcome'],
    follow_ups: ['How do you stay updated in fast-moving AI field?', 'What is your learning process?'],
    hint_ladder: ['What concept did you need to learn?', 'How did you learn it?', 'How did you apply it?'],
    time_limit_min: 4,
  },

  // ───────────────────────────────────────────────────────────
  // Additional SWE fundamentals to reach ~60 per track
  // ───────────────────────────────────────────────────────────
  {
    id: 'swe-dsa-stack-01',
    track: 'swe',
    section: 'fundamentals',
    topic: ['stack', 'queue'],
    difficulty: 1,
    years: [2],
    type: 'conceptual',
    prompt: 'Explain stack vs queue. How would you implement a queue using two stacks? What is the amortized complexity?',
    reference_answer: 'Stack LIFO, queue FIFO. Two stacks: push to in-stack, pop from out-stack, transfer when out empty. Amortized O(1).',
    key_points: ['LIFO vs FIFO', 'Two-stack implementation', 'Amortized O(1) explanation', 'Example'],
    common_mistakes: ['Says O(n) always', 'No amortized analysis', 'Wrong transfer logic'],
    follow_ups: ['How to implement stack using queues?', 'What is deque?'],
    hint_ladder: ['What order does each use?', 'How can you reverse order with stack?', 'When do you need to move elements?'],
    time_limit_min: 5,
  },
  {
    id: 'swe-dsa-tree-01',
    track: 'swe',
    section: 'fundamentals',
    topic: ['trees', 'bst'],
    difficulty: 2,
    years: [3],
    type: 'conceptual',
    prompt: 'What is a Binary Search Tree? How does insertion and search work? What is the worst-case and how to fix it?',
    reference_answer: 'BST left < node < right. Insert/search O(h) where h height, worst O(n) if skewed, fix via AVL/Red-Black balancing O(log n).',
    key_points: ['BST property left < node < right', 'O(h) complexity', 'Worst O(n) skewed', 'Balancing via AVL/Red-Black'],
    common_mistakes: ['Forgets BST property', 'Says always O(log n)', 'No balancing'],
    follow_ups: ['AVL vs Red-Black tradeoff?', 'How to do inorder traversal?'],
    hint_ladder: ['What rule makes search fast?', 'What if you insert sorted numbers?', 'How to keep tree balanced?'],
    time_limit_min: 4,
  },
  {
    id: 'swe-coding-reverse-01',
    track: 'swe',
    section: 'problem_solving',
    topic: ['strings', 'two-pointers'],
    difficulty: 1,
    years: [2],
    type: 'coding',
    prompt: 'Reverse a string in-place and check if it is a palindrome ignoring non-alphanumeric and case. Explain complexity.',
    reference_answer: 'Two pointers from ends, skip non-alphanumeric, compare lowercased. O(n) time O(1) extra space.',
    key_points: ['Two pointers approach', 'Handles non-alphanumeric', 'Case-insensitive', 'O(n) time O(1) space'],
    common_mistakes: ['Creates new string and claims O(1) space', 'No non-alphanumeric handling', 'Case sensitive'],
    follow_ups: ['What if you need to reverse words in sentence?', 'How to check palindrome in linked list?'],
    hint_ladder: ['How to compare from both ends?', 'What characters should be ignored?', 'Can you do without extra memory?'],
    time_limit_min: 8,
  },
  {
    id: 'swe-coding-merge-01',
    track: 'swe',
    section: 'problem_solving',
    topic: ['arrays', 'sorting', 'merge'],
    difficulty: 2,
    years: [3],
    type: 'coding',
    prompt: 'Merge two sorted arrays into one sorted array in-place (first array has extra space). What is complexity?',
    reference_answer: 'Three pointers from end: i=m-1, j=n-1, k=m+n-1, fill largest first. O(m+n) time O(1) space.',
    key_points: ['Three pointers from end', 'Fills from largest', 'O(m+n) time', 'O(1) extra space'],
    common_mistakes: ['Starts from beginning and overwrites', 'Uses extra array and claims O(1)', 'Wrong complexity'],
    follow_ups: ['What if you have k sorted arrays?', 'Merge intervals problem?'],
    hint_ladder: ['If you start from beginning, what gets overwritten?', 'What if you fill from the end?', 'Which element should go last?'],
    time_limit_min: 8,
  },
  {
    id: 'swe-fund-recursion-01',
    track: 'swe',
    section: 'fundamentals',
    topic: ['recursion', 'complexity'],
    difficulty: 1,
    years: [2],
    type: 'conceptual',
    prompt: 'Explain recursion vs iteration. What is stack overflow and tail recursion? Give example of factorial or Fibonacci.',
    reference_answer: 'Recursion function calls itself, uses call stack. Iteration loops. Stack overflow too many calls. Tail recursion call is last operation, can be optimized to loop.',
    key_points: ['Recursion uses call stack', 'Stack overflow explanation', 'Tail recursion', 'Example factorial/Fibonacci'],
    common_mistakes: ['Says recursion always better', 'No stack overflow', 'No tail recursion'],
    follow_ups: ['How to convert recursion to iteration?', 'What is memoization?'],
    hint_ladder: ['What happens when function calls itself?', 'What if it calls itself 1M times?', 'What if recursive call is last line?'],
    time_limit_min: 4,
  },
  {
    id: 'swe-behavioural-03',
    track: 'swe',
    section: 'behavioural',
    topic: ['behavioural', 'leadership'],
    difficulty: 2,
    years: [3],
    type: 'behavioural',
    prompt: 'Tell me about a time you showed leadership without formal authority.',
    reference_answer: 'STAR: noticed gap, took initiative, organized, delegated, delivered, learned.',
    key_points: ['STAR', 'Initiative without title', 'Team outcome', 'Learning'],
    common_mistakes: ['Says was manager', 'No initiative', 'No outcome'],
    follow_ups: ['How do you motivate teammates?', 'How handle someone not contributing?'],
    hint_ladder: ['When did you step up?', 'What did you do?', 'What was result?'],
    time_limit_min: 4,
  },
  {
    id: 'swe-wrapup-01',
    track: 'both',
    section: 'wrap_up',
    topic: ['questions', 'closing'],
    difficulty: 1,
    years: [2, 3],
    type: 'wrap_up',
    prompt: 'Do you have any questions for me about the role, team, or interview process?',
    reference_answer: 'Good questions: team, growth, tech stack, challenges, culture. Avoid salary early, or questions answered already.',
    key_points: ['Asks thoughtful questions', 'Shows interest in team/growth', 'Not only about salary', 'Engages'],
    common_mistakes: ['No questions', 'Only salary', 'Question already answered'],
    follow_ups: [],
    hint_ladder: ['What would help you decide if role is good fit?', 'What about team or growth?', 'What about tech challenges?'],
    time_limit_min: 2,
  },
]

export function getQuestionById(id: string): InterviewQuestion | undefined {
  return QUESTION_BANK.find(q => q.id === id)
}

export function getQuestionsByTrack(track: InterviewTrack, year: InterviewYear): InterviewQuestion[] {
  return QUESTION_BANK.filter(q => (q.track === track || q.track === 'both') && q.years.includes(year))
}

export function getQuestionsBySection(track: InterviewTrack, year: InterviewYear, section: InterviewQuestion['section']): InterviewQuestion[] {
  return getQuestionsByTrack(track, year).filter(q => q.section === section)
}

export function getCodingQuestions(track: InterviewTrack): InterviewQuestion[] {
  return QUESTION_BANK.filter(q => q.type === 'coding' && (q.track === track || q.track === 'both'))
}

export function getRandomQuestions(
  track: InterviewTrack,
  year: InterviewYear,
  section: InterviewQuestion['section'],
  count: number,
  excludeIds: Set<string> = new Set(),
): InterviewQuestion[] {
  const pool = getQuestionsBySection(track, year, section).filter(q => !excludeIds.has(q.id))
  const shuffled = [...pool].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}
